services:
  yocto-builder:
    build:
      context: .
      args:
        USERNAME: ubuntu
    container_name: yocto-builder
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - .:/home/ubuntu
