services:
  yocto-builder:
    build:
      context: .
      args:
        USERNAME: user
    container_name: yocto-builder
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/user
